name: Push to Swell

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Configure Swell CLI
        env:
          SWELL_CONFIG: ${{ secrets.SWELL_CONFIG }}
        run: |
          mkdir -p ~/.swell
          echo "$SWELL_CONFIG" > ~/.swell/config.json

      - name: Install dependencies and push to Swell
        run: |
          npm i -g @swell/cli@latest
          npm ci
          swell app push --force
          swell app version patch -m "Patch release" -y
          swell app release -y